//
// Generated file, do not edit! Created by nedtool 5.1 from inet_bk/linklayer/ext/ExtFrame.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __INET_EXTFRAME_M_H
#define __INET_EXTFRAME_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

/**
 * Class generated from <tt>inet_bk/linklayer/ext/ExtFrame.msg:21</tt> by nedtool.
 * <pre>
 * message ExtFrame
 * {
 *     uint8 data[];
 * }
 * </pre>
 */
class INET_API ExtFrame : public ::omnetpp::cMessage
{
  protected:
    uint8_t *data; // array ptr
    unsigned int data_arraysize;

  private:
    void copy(const ExtFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ExtFrame&);

  public:
    ExtFrame(const char *name=nullptr, short kind=0);
    ExtFrame(const ExtFrame& other);
    virtual ~ExtFrame();
    ExtFrame& operator=(const ExtFrame& other);
    virtual ExtFrame *dup() const override {return new ExtFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setDataArraySize(unsigned int size);
    virtual unsigned int getDataArraySize() const;
    virtual uint8_t getData(unsigned int k) const;
    virtual void setData(unsigned int k, uint8_t data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExtFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExtFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_EXTFRAME_M_H

